### PR TITLE
CPU over-utilization patch

### PR DESCRIPTION
**Pull request by clucksoft**
D2 doesn't sleep properly each frame and uses way more cpu than it needs to. This fix is described at: http://d2mods.info/forum/viewtopic.php?f=8&t=62379&sid=31c24eb3e296cecbdcc8f371c8c69a07

The jump they NOP for singleplayer seems to be the right one for regular online play, I assume the multiplayer part is for hosting a tcp/ip game. I didn't patch that since I don't feel like testing it. 
I also NOP the two instructions before the jump since they have no purpose without it.

This cuts my D2 cpu usage in half without adversely affecting gameplay.
The same problem exists while in menus, but this doesn't fix that.. I'll try and figure that out too.

### CODE REVIEW

**Comment by slayergod13** [comment]
This sounds great! If you give up on the menu problem let me know, otherwise I'll hold off on putting out a new version for that.

**Comment by slayergod13** [comment]
Yes, I am seeing about a 50% drop in CPU usage with this patch. But I am also seeing about 1/4 the framerate, going from 200+ to about 56. Are you seeing this same drop in performance?

**Comment by clucksoft** [comment]
The game itself runs at 25 fps, right? That framerate loss shouldn't be a loss in actual performance, it's just no longer processing tons of unnecessary frames due to not sleeping.

**Comment by slayergod13** [comment]
Yes, in single player its fixed at 25 fps. Which should mean that anything over that is wasted, I did not notice any lag with the patch running, just the loss of frame rate.

I don't have much time to play these days, but I will do a little more testing with it to try and confirm this.

**Comment by clucksoft** [comment]
You've probably already searched and found this, but here's a reference on that: http://diablo2.diablowiki.net/FPS#Diablo.27s_Internal_Speed

The menu issue is probably going to take a lot more time. I read that D2Loader may have implemented a fix for that, so I might be able to see how it does it (I don't see any source for it though, so will be trickier).

**Pull request merged**
