### PR TITLE
BH AutoInject

### PR DESCRIPTION
**Pull request by clucksoft**
Added a mode to the injector to auto inject into new instances. My other changes were to get it to compile in VS2013, hopefully that's not an issue.

### CODE REVIEW

**Comment by clucksoft** [comment]
Going to clean this up a bit more, maybe put out a release and then see if you are interested in merging.

**Comment by slayergod13** [comment]
Sorry, I've just been busy with work and haven't had time to review it yet.

**Comment by clucksoft** [comment]
No problem. I've been using it for several days without any issues but the code still could use a bit of a clean up. Will get that taken care of sometime this weekend.

**Comment by clucksoft** [comment]
Ok, this is good to go now. I think auto-injection into new D2 processes is a very useful feature, and pretty much the only thing I noticed was wrong with BH. I launch it with '-o 2' and now it just sits there for days injecting whenever I launch the game. Much better!

**Pull request merged**
